/*Copyright (c) 2015-2016 wavemakervcs1.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemakervcs1.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemakervcs1.com*/

package com.wavemakervcs1.testsampledb738.hrdb23;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;




/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="CUSTOMER"
    ,schema="PUBLIC"
)
public class Customer  implements java.io.Serializable
 {


private Integer custId;
private String custName;
private Integer age;
private String address;
private Integer salary;

    public Customer() {
    }



     @Id @GeneratedValue(strategy=IDENTITY)

    

    @Column(name="CUST_ID", nullable=false, length=4)
    public Integer getCustId() {
        return this.custId;
    }
    
    public void setCustId(Integer custId) {
        this.custId = custId;
    }

    

    @Column(name="CUST_NAME", nullable=false, length=30)
    public String getCustName() {
        return this.custName;
    }
    
    public void setCustName(String custName) {
        this.custName = custName;
    }

    

    @Column(name="AGE", nullable=false, length=3)
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }

    

    @Column(name="ADDRESS", nullable=false, length=30)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    

    @Column(name="SALARY", nullable=false, length=5)
    public Integer getSalary() {
        return this.salary;
    }
    
    public void setSalary(Integer salary) {
        this.salary = salary;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof Customer) )
		 return false;

		 Customer that = ( Customer ) o;

		 return ( (this.getCustId()==that.getCustId()) || ( this.getCustId()!=null && that.getCustId()!=null && this.getCustId().equals(that.getCustId()) ) );

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getCustId() == null ? 0 : this.getCustId().hashCode() );

         return result;
     }


}

