/*Copyright (c) 2015-2016 wavemakervcs1.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemakervcs1.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemakervcs1.com*/

package com.wavemakervcs1.testsampledb738.hrdb23;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;




/**
 * EVcustomerorderdetailsId generated by hbm2java
 */
@Embeddable
public class EVcustomerorderdetailsId  implements java.io.Serializable
 {


private Integer orderId;
private String custName;
private Integer amount;
private Date date;

    public EVcustomerorderdetailsId() {
    }




    

    @Column(name="ORDER_ID")
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    

    @Column(name="CUST_NAME", length=30)
    public String getCustName() {
        return this.custName;
    }
    
    public void setCustName(String custName) {
        this.custName = custName;
    }

    

    @Column(name="AMOUNT")
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    @Temporal(TemporalType.DATE)

    @Column(name="DATE", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof EVcustomerorderdetailsId) )
		 return false;

		 EVcustomerorderdetailsId that = ( EVcustomerorderdetailsId ) o;

         return ( (this.getOrderId()==that.getOrderId()) || ( this.getOrderId()!=null && that.getOrderId()!=null && this.getOrderId().equals(that.getOrderId()) ) )
 && ( (this.getCustName()==that.getCustName()) || ( this.getCustName()!=null && that.getCustName()!=null && this.getCustName().equals(that.getCustName()) ) )
 && ( (this.getAmount()==that.getAmount()) || ( this.getAmount()!=null && that.getAmount()!=null && this.getAmount().equals(that.getAmount()) ) )
 && ( (this.getDate()==that.getDate()) || ( this.getDate()!=null && that.getDate()!=null && this.getDate().equals(that.getDate()) ) );

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getOrderId() == null ? 0 : this.getOrderId().hashCode() );
         result = 37 * result + ( getCustName() == null ? 0 : this.getCustName().hashCode() );
         result = 37 * result + ( getAmount() == null ? 0 : this.getAmount().hashCode() );
         result = 37 * result + ( getDate() == null ? 0 : this.getDate().hashCode() );

         return result;
     }


}

