/*Copyright (c) 2015-2016 wavemakervcs1.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemakervcs1.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemakervcs1.com*/

package com.wavemakervcs1.testsampledb738.hrdb23;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;




/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="ORDERS"
    ,schema="PUBLIC"
)
public class Orders  implements java.io.Serializable
 {


private Integer orderId;
private Integer customerId;
private Date date;
private Integer amount;

    public Orders() {
    }



     @Id @GeneratedValue(strategy=IDENTITY)

    

    @Column(name="ORDER_ID", nullable=false, length=4)
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    

    @Column(name="CUSTOMER_ID", length=4)
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    @Temporal(TemporalType.DATE)

    @Column(name="DATE", nullable=false, length=1)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    

    @Column(name="AMOUNT", length=10)
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof Orders) )
		 return false;

		 Orders that = ( Orders ) o;

		 return ( (this.getOrderId()==that.getOrderId()) || ( this.getOrderId()!=null && that.getOrderId()!=null && this.getOrderId().equals(that.getOrderId()) ) );

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getOrderId() == null ? 0 : this.getOrderId().hashCode() );

         return result;
     }


}

