/*Copyright (c) 2015-2016 wavemakervcs1.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemakervcs1.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemakervcs1.com*/

package com.wavemakervcs1.testsampledb738.hrdb23.dao;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Repository;
import org.springframework.orm.hibernate4.HibernateTemplate;

import com.wavemaker.runtime.data.dao.WMGenericDaoImpl;

import com.wavemakervcs1.testsampledb738.hrdb23.*;
/**
 * Specifies methods used to obtain and modify EVcustomerorderdetails related information
 * which is stored in the database.
 */
@Repository("hrdb23.EVcustomerorderdetailsDao")
public class EVcustomerorderdetailsDao extends WMGenericDaoImpl <EVcustomerorderdetails, EVcustomerorderdetailsId> {

   @Autowired
   @Qualifier("hrdb23Template")
   private HibernateTemplate template;

   public HibernateTemplate getTemplate() {
        return this.template;
   }
}

