/*Copyright (c) 2015-2016 wavemakervcs1.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemakervcs1.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemakervcs1.com*/


package com.wavemakervcs1.testsampledb738.hrdb23.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.model.CustomQuery;
import com.wavemaker.runtime.data.exception.QueryParameterMismatchException;

public interface Hrdb23QueryExecutorService {
    Page<Object> executeInnerJoinQuery(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeLeftOuterJoinQuery(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeRightOuterJoinquery(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeFullOuterJoinQuery(Pageable pageable) throws QueryParameterMismatchException;
	int executeInsertQuery() throws QueryParameterMismatchException;
    Page<Object> executeGetViewData(Pageable pageable) throws QueryParameterMismatchException;

	
	Page<Object> executeWMCustomQuerySelect(CustomQuery query, Pageable pageable) ;

	int executeWMCustomQueryUpdate(CustomQuery query) ;
}

