/*Copyright (c) 2015-2016 wavemakervcs1.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemakervcs1.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemakervcs1.com*/


package com.wavemakervcs1.testsampledb738.hrdb23.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.util.HashMap;
import java.util.Map;
import java.util.Collections;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;

import com.wavemaker.runtime.data.model.CustomQuery;
import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.exception.QueryParameterMismatchException;

@Service
public class Hrdb23QueryExecutorServiceImpl implements Hrdb23QueryExecutorService {
	private static final Logger LOGGER = LoggerFactory.getLogger(Hrdb23QueryExecutorServiceImpl.class);

	@Autowired
	@Qualifier("hrdb23WMQueryExecutor")
	private WMQueryExecutor queryExecutor;

	@Transactional(value = "hrdb23TransactionManager")
	@Override
	public Page<Object> executeInnerJoinQuery(Pageable pageable)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        return queryExecutor.executeNamedQuery("InnerJoinQuery", params, pageable);
	}
	@Transactional(value = "hrdb23TransactionManager")
	@Override
	public Page<Object> executeLeftOuterJoinQuery(Pageable pageable)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        return queryExecutor.executeNamedQuery("LeftOuterJoinQuery", params, pageable);
	}
	@Transactional(value = "hrdb23TransactionManager")
	@Override
	public Page<Object> executeRightOuterJoinquery(Pageable pageable)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        return queryExecutor.executeNamedQuery("RightOuterJoinquery", params, pageable);
	}
	@Transactional(value = "hrdb23TransactionManager")
	@Override
	public Page<Object> executeFullOuterJoinQuery(Pageable pageable)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        return queryExecutor.executeNamedQuery("FullOuterJoinQuery", params, pageable);
	}
	@Transactional(value = "hrdb23TransactionManager")
	@Override
	public int executeInsertQuery()
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        return queryExecutor.executeNamedQueryForUpdate("InsertQuery", params);
	}
	@Transactional(value = "hrdb23TransactionManager")
	@Override
	public Page<Object> executeGetViewData(Pageable pageable)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        return queryExecutor.executeNamedQuery("getViewData", params, pageable);
	}

	@Transactional(value = "hrdb23TransactionManager")
	@Override
	public Page<Object> executeWMCustomQuerySelect(CustomQuery query, Pageable pageable) {
	    return queryExecutor.executeCustomQuery(query, pageable);
	}

	@Transactional(value = "hrdb23TransactionManager")
    @Override
    public int executeWMCustomQueryUpdate(CustomQuery query) {
        return queryExecutor.executeCustomQueryForUpdate(query);
    }
}

